### ISSUE TITLE
Fail more gracefully when optional dependencies are missing

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#134]
PCASPy and EPICS are optional dependencies. When they are missing, but the user attempts to use something that depends on them, the system should fail gracefully and inform the user what went wrong and why.

Right now, the exceptions thrown when attempting to run an EPICS device without proper dependencies are not clear as to what failed or what can be done about it, and can even be misleading.

Related to #135.

**Comment by MichaelWedel** [comment]
As per your suggestion I will make a start by raising more meaningful `PlanktonException`s with better text.
