### ISSUE TITLE
Make device Interfaces self-documenting

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#141]
Following some user feedback acquired by @OwenArnold that pointed out device `Interfaces` could be self-documenting with regard to the PVs/commands they expose.

This could be implemented in the respective Adapter, potentially using the docstrings of the exposed properties/methods. These can be extracted using the `inspect`-module.

**Comment by dmichel76** [comment]
Yes, the idea I suggested to @OwenArnold was to somehow be able to query what the protocol is, as it's easy to forgot or not have the required documentation at hand. Happy to test it and give some feedback once implemented.

**Comment by OwenArnold** [comment]
@dmichel76 I think it would be very useful to have you review this functionality. We'd definitely take you up on that.

**Comment by MichaelWedel** [comment]
@dmichel76 thanks for the feedback, it's something we did not have on the screen so far. I like the idea of documenting these things because it also helps keeping the knowledge about a device alive somewhere.

Regarding the way this can be queried there are different possibilities. One is certainly the control server, but another one could be the `plankton.py`-script, which could in the first step simply print this information if a flag is provided, e.g.

```
$ ./plankton.py -p epics chopper --interface
Device: Chopper
Protocol: EPICS
PVs:
    Spd: Speed setpoint in Hz
    ActSpd: Actual speed of the chopper in Hz
    ...
```
