### ISSUE TITLE
Setting multiple properties at the same time

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#143]
A question that came up during a meeting with the IBEX team is whether multiple values could be set at once using `control.py` from the command line. 

My initial response was that this was a scenario where it might be more appropriate to write a script rather than using the command line utility.

Thinking about it, however, there may be scenarios where it is important to set multiple values atomically. That is, to ensure they are all set during the same cycle. 

Right now, due to the way the processing loop works, I think only one RPC command can be processed per cycle? If so, setting 10 different variables would get split across 10 cycles (1 second by default) even if you do it using a script. Even if this is not the case, it's impossible to ensure multiple properties are set during the same cycle.

We should consider:

* In the control client, making it possible to set multiple properties in one go using a dictionary or similar
* Exposing the above in the command line interface somehow (bonus, non-essential)
* Adjusting the way our processing loop works to permit multiple commands per cycle (the same goes for the adapters?)

With everything else going on, this is quite low priority for now, unless it becomes an issue in real usage, so putting it in the backlog.

**Comment by MichaelWedel** [comment]
I agree that it is more of a backlog thing, but it should be easy. We could add a function in `Device`:

```
def set_parameters(self, new_parameters):
    for param, new_value in new_parameters.items():
        if param in dir(self):
            setattr(self, param, new_value)
```

I didn't get it to work via the command line, but in a script it works:

```
a = ControlClient()
dev = a.get_object('device')

dev.set_parameters({'name': 'foo', 'type': 'bar'})
```

**Comment by MichaelWedel** [comment]
After some syntax related experimentation I ended up with this which seems to work:

```
./plankton-control.py device set_parameters '{"name": "foo", "type": "bar"}'
```

**Comment by MikeHart85** [comment]
Nice, I like it! :+1:

**Comment by MichaelWedel** [comment]
This is something that could even go into `DeviceBase` now that this exists.
