### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#146]
We have a [Contributing.md](https://github.com/DMSC-Instrument-Data/plankton/blob/master/docs/Contributing.md) document, but this describes how to write devices rather than how to contribute to the framework or repository.

We should rename the existing document accordingly and create contribution guidelines that describe policies and procedures for things like:

* Opening issues
* Submitting pull requests
* Target response times we'll aim for

In his NOBUGS talk, @peterfpeterson mentioned that providing a `CONTRIBUTING.md` file in the top directory of a repository is good / common practice. We should consider putting it there rather than in `/docs/`.

**Comment by MichaelWedel** [comment]
Agreed.
