### ISSUE TITLE
Create a MODBUS interface

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/lewis#160]
At ISIS we are trying to write an emulator for a Eurotherm nanodac http://www.eurotherm.co.uk/products/recorders/graphic/nanodac. We plan to talk to the device using MODBUS TCP and already have an IOC (written elsewhere). The use case for writing an emulator is that we have yet to purchase the equipment and we would like to test the IOC.

We are happy to do the actual device emulator ourselves but it would require MODBUS support within plankton.

**Comment by MikeHart85** [comment]
Is the IOC available somewhere, for reference and testing?

**Comment by DominicOram** [comment]
The support module is at https://github.com/ISISComputingGroup/EPICS-nanodac and an example IOC at https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket1843_nanodac_support/NANODAC.
