### ISSUE TITLE
Update Copyright Notices for 2017

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#179]
As noted in #175, copyright notices should be updated, to read:

> Copyright (C) 2016-2017 European Spallation Source ERIC

This is technically optional; we could leave it as 2016 and continue using 2016 even in new files. 

But if we do want to update, we should do it wholesale in all files across the project.

See also: https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by MichaelWedel** [comment]
I think we should do this sooner rather than later. It's an automated thing so it won't take long. It should be the (almost) last thing before the release because it touches every single file so it might cause problems.
