### ISSUE TITLE
Multiple interface, interface documentation

### ISSUE THREAD

**Issue by OwenArnold** [ISISComputingGroup/lewis#190]
Follows on somewhat from #141, for devices with multiple interfaces it's not clear how you continue with the `-i` option to get the information from one of the interfaces. For example:
```
(venv)/Users/spu92482/sources/lewis (master)$./lewis.py --show-interface julabo
2017-01-30 19:10:54,612 INFO lewis.DeviceBase: Creating device, setting up state machine
An error occurred:
Failed to find protocol 'None' for device 'julabo'. Available protocols are: 
    julabo-version-2
    julabo-version-1
```

Needs to be discussed before being assigned a milestone and priority.

**Comment by MichaelWedel** [comment]
It should work using `lewis -p julabo-version-2 -i julabo`.

**Comment by MikeHart85** [comment]
Perhaps just a matter of rewording the error slightly to something like:
> Must specify protocol (using -p option) for devices that have more than one. Available protocols are: ...

**Comment by OwenArnold** [comment]
@MikeHart85 yes, that was what was missing.
