### ISSUE TITLE
Any new improvements?

### ISSUE THREAD

**Issue by chansdad** [ISISComputingGroup/lewis#276]
This is one of the many useful projects i have seen in the age of IOT. anyone working on this actively? Would like to have some new features added to it . Most importantly adding support for device types. so presently , we have to create "A Device" that can be controlled on a single port , great if you have a single device and could be useful in a factory or plant setting . if it is a device type , we can have multiple devices and be able to control all the devices , essentially it will allow a large volume of devices and lift the limitation on the total number of devices that can be simulated on a host as # of ports are limited. Also plugins to auto create the device or device type files based on some markup language as opposed to writing python code . 

Thanks

**Comment by mattclarke** [comment]
Hi.
We are not doing much with lewis at the moment because it currently meets our requirements. 
However, some of your suggestions are interesting, so we will look into them next time we are working on the code base.

Thanks for getting in touch :)

**Comment by chansdad** [comment]
Thanks . Repurposed it for the time being , by writing the device objects into a array .. While in my case devices dont interact with one another , would be good to really utilize the state machine to set different conditions in the device . For now each of the objects state is updated by way of updating its properties. Further more one of the key things i noticed is state is not persisted across restarts which is significant ..  Also telnet is a big no no to control device behavior .I warpped the commands in a rest api . Kind of hard coded for now , I am not an expert level python programmer , hacked my way and got it to do what i wanted , but this product sure has a TON of potential with the right set of features..

**Comment by mattclarke** [comment]
Can you create a draft PR, so we can see what you have done please?
It might be something we could use/add

**Comment by chansdad** [comment]
This was on my plate for a while , I will start cleaning up a bit and will write up something .

**Comment by chansdad** [comment]
Unfortunately did not get time to create a draft PR . are you still enhancing this project?

**Comment by mattclarke** [comment]
Not so much, it currently has the functionality the main contributors generally need.
But if we require new functionality then we will implement it.

Still happy to look at and discuss PRs from other people though :D
