### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/lewis#286]
For release 1.2.2 I pinned `scanf==1.4.1` as one of the scanf releases was broken for python 3.7. Latest releases are not broken, we should update and confirm it works

**Comment by KacperKlys** [comment]
Hi @DominicOram, I have encountered problem with lewis 1.2.2 on ubuntu 20 with python 3.8.2 and I believe it is connected with this issue. scanf 1.4.1 still causes some errors on python 3.8 (for 3.7.7 it works ok). I have installed the newest version of scanf (1.5.1) and it seems to be working with Python 3.8.2 and lewis 1.2.2

**Comment by mattclarke** [comment]
Unpinned the version, shout if it doesn't work
