### ISSUE TITLE
Python binaries for lewis simulators

### ISSUE THREAD

**Issue by dheeraj539** [ISISComputingGroup/lewis#299]
I have created a simulator for a device using epics interface. Now I need to deploy it on a server and run it from there. Is there a way to deploy only binaries to the server instead of coping entire code of my simulator and then run it?

**Comment by mattclarke** [comment]
I've never used it but you could try something like PyInstaller (https://www.pyinstaller.org/).
From what I understand that would create a standalone exe you can deploy
