### ISSUE TITLE
Confusion of concepts now in README

### ISSUE THREAD

**Issue by OwenArnold** [ISISComputingGroup/lewis#31]
The README mainly seems geared to explain the chopper instance you created. It also starts out by describing the state machine. As plankton will be used for multiple devices, the documentation should be re-ordered. 

What do you think @MichaelWedel @MikeHart85 ?

**Comment by MichaelWedel** [comment]
I agree with this, but for the entire thing to become more coherent the `basic_simulated_chopper.py` file needs to move somewhere else. This is probably a part of #30, so it would make sense to finish #30 first.
