### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#47]
We've been somewhat frivolous with naming conventions for functions.

Some functions use `lowercase_with_underscores()` while others `useCamelCase()`. 

We should standardize and update before the code base grows much bigger.

I think we settled on camelCase when we briefly talked about this before? Any objections / other ideas?

**Comment by MichaelWedel** [comment]
I vote for `CamelCase` for classes, `dromedarCase` for methods and `lowercase_with_underscores` for free functions and local variables.

**Comment by MikeHart85** [comment]
Sounds good to me.

`CAPS_AND_UNDERSCORES` to indicate variables intended to be used as constants?

**Comment by MichaelWedel** [comment]
Do we have that anywhere?

**Comment by MikeHart85** [comment]
I don't think we do yet. Just think we should settle on a convention for later.

The `epics` variable defined in bindings.py should arguably only be used for lookup and not change at runtime... might apply to that.

There's no straightforward way to enforce constness in Python, but some people like to use all caps to signify intent.

Personally, I think I'd prefer leaving it lowercase, and not to make assumptions that aren't enforced anyway.

**Comment by MichaelWedel** [comment]
I agree to the last sentence. Enum-values could be made upper case to make them easier to spot.

**Comment by MichaelWedel** [comment]
I think one actual action out of this should be adding a `contributing` document somewhere where this goes into a "Coding standards" section.

**Comment by MikeHart85** [comment]
Should we use the Wiki feature on Git for this and other documentation?

**Comment by MichaelWedel** [comment]
In my opinion the best thing is having all documentation in the source tree. Then there's one place for everything and easier to keep track of. Mantid is moving towards this approach and it's much easier to maintain, test etc.

Whenever there is time I'm looking further into #10, for now I think we should just have a markdown file.

**Comment by MichaelWedel** [comment]
This has been somewhat superseded by reality, we got rid of the `dromedarCase`-methods, so now all functions are `underscore_case`. Perhaps this should also be in a section in the contribution guidelines.

**Comment by mattclarke** [comment]
See PEP8
