### ISSUE TITLE
Provide certain behavior as separate classes/functions

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#81]
Many default states for the devices have very similar code, because essentially they are "approach a target value linearly with a given rate of change". There should be exactly one place in the code where this is implemented.

My suggestion would be to create a new module in `core` for this. Maybe even in a sub-module called `behavior` or something along those lines.

**Comment by MikeHart85** [comment]
We should consider non-linear approaches as well. Perhaps this could be implemented with a general `approach` function that takes a lambda/function reference to determine how exactly the approach is calculated. An `approach_linear` and similar could also be provided, which would call the general `approach` with appropriate pre-made functions.

Another thing to consider for such a library of general functionality is pseudo-random number generation. To keep the simulation deterministic even when "randomness" is required by device behaviour, we should have an easy way for the device developer to get pseudo-random numbers that are reproducible when necessary (and randomly seeded when not).

**Comment by MichaelWedel** [comment]
Yes, let's think about how we could implement this in a good way. I like the idea of just exchanging the approach-function. That would also make it easy to exchange to something different, in case of super special behavior.

**Comment by MichaelWedel** [comment]
This also needs to be part of Release 1.0 so that users have at least some functionality in this area.
