### ISSUE TITLE
Update documentation once Communication Redesign completed

### ISSUE THREAD

**Issue by MikeHart85** [ISISComputingGroup/lewis#89]
The front-facing `README.md` will need to be updated once design changes [discussed here](https://github.com/DMSC-Instrument-Data/documents/blob/master/design/plankton/CommunicationLayerDesign.md) are applied.

Perhaps this would also be a good time to split the documentation up a bit by topic, put most of the content in `/docs/`, and make the front-facing README leaner with links to the various topics. 

A concise overview with links to more tends to make for a more accessible entry point... Screenshots would also be a great addition, I think.

**Comment by OwenArnold** [comment]
@MikeHart85 / @MichaelWedel I think this is somehow tied to the #108. But we want all documentation to look good for the Release 1.0

**Comment by MichaelWedel** [comment]
Can this be closed now?

**Comment by OwenArnold** [comment]
@MichaelWedel I'm waiting on @MikeHart85 to split the Framework Details off the front README. I'll do it if nothing gets pushed in the next couple of hours.
