### ISSUE TITLE
Add unit tests for statemachine

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#9]
The statemachine currently has no unit tests. There should be a few that use `mock` to make sure the right functions are called in the right states and so on.

**Comment by MichaelWedel** [comment]
@MikeHart85 I assigned you because you know most about the state machine. It's probably good to wait until #6 is complete, because of file location.

**Comment by OwenArnold** [comment]
@MichaelWedel @MikeHart85 This sounds like a good idea. 👍 for using mock.
