### ISSUE TITLE
Communication Layer re-design

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#91]
This is an umbrella-issue to host the changes required for the re-design of the communication layer discussed [here](https://github.com/DMSC-Instrument-Data/documents/blob/master/design/plankton/CommunicationLayerDesign.md).
- [x] Move run-logic of adapters to new `Environment` class (#92)
- [x] Implement new package structure
- [x] Split chopper into Adapter and Device
- [x] Split Linkam into Adapter and Device
- [x] Add contribution guideline document

Postponed to 1.1:
- Create build files for PyPI package

**Comment by OwenArnold** [comment]
All done. Well done @MichaelWedel!
